---
apiVersion: aioperator.io/v1alpha1
kind: PRReconciliationRule
metadata:
  name: production-approval
  namespace: ai-operator-system
  labels:
    environment: production
    automation-level: low
spec:
  # This rule applies to PRs targeting production
  selector:
    labels:
      include:
        - "production"
      exclude:
        - "do-not-merge"
        - "wip"
    baseBranch: "main"

  # AI instruction for decision-making (human approval required)
  instruction: |
    You are an AI operator reviewing a production environment pull request.

    **IMPORTANT:** Production changes always require human approval.

    **Pull Request Context:**
    - PR #{{pr.number}}: {{pr.title}}
    - Author: {{pr.author}}
    - Labels: {{pr.labels}}
    - CI Status: {{pr.ciStatus}}
    - Mergeable: {{pr.mergeable}}
    - Reviews: {{pr.reviews}}

    **Decision Rules:**

    1. **NEVER AUTO-MERGE** - This is a production environment

    2. **ESCALATE** if CI passed and ready for human review:
       - CI status is "SUCCESS"
       - PR is mergeable (no conflicts)
       - Add label "pending-human-approval"
       - Add comment: "✅ CI passed. Production PR ready for senior maintainer approval."

    3. **CLOSE** if:
       - PR author explicitly requested closure (check for comments like "closing", "no longer needed")
       - Add comment explaining why it was closed

    4. **WAIT** if:
       - CI status is "PENDING" (tests still running)
       - Do nothing, check again next reconciliation

    5. **ESCALATE** with alert if:
       - CI status is "FAILURE" or "ERROR"
       - Add label "ci-failed"
       - Add comment: "❌ CI failed. Please fix before requesting approval."

    **Output Format:**
    Return a JSON object:
    {
      "action": "escalate",  // one of: "wait", "escalate", "close" (NEVER "merge")
      "reason": "Production PR requires senior maintainer approval per governance policy"
    }

  # Argo CD not needed for production approval workflow
  argocdEnabled: false

  # Check less frequently for production (every 60 seconds)
  reconciliationInterval: 60

  # Note: mergeMethod is not used since we never auto-merge production
  mergeMethod: "SQUASH"
